### ISSUE TITLE
GenerateConnectivityFile ?

### ISSUE THREAD

**Issue by xiaohumengdie** [ClimateGlobalChange/tempestextremes#34]
HI  !
      I can get the ne30  adjacency list, the command is  GenerateConnectivityFile --in_mesh ne30np4_091226_pentagons.nc --out_connect outCSne30_connect.txt. and I got a error(ne120 adjacency list), the error : 

GenerateConnectivityFile --in_mesh ne120np4_pentagons_100310.nc --out_connect outCSne120_connect.txt
Arguments:
  --in_mesh <string> ["ne120np4_pentagons_100310.nc"] 
  --in_concave <bool> [false] 
  --out_type <string> ["FV"] [FV|CGLL|DGLL]
  --out_np <integer> [4] 
  --out_connect <string> ["outCSne120_connect.txt"] 
------------------------------------------------------------
Loading mesh
..SCRIP Format File detected
..3107526 duplicate nodes detected
..Mesh size: Nodes [780484] Elements [777602]
..Done
Calculating connectivity information
..Mesh size: Edges [1558112]
..Done
Converting mesh to connectivity format
..EXCEPTION (/home/cesm01/software/tempestextremes-2.2.1/src/base/SimpleGrid.cpp, Line 794) EdgeMap FacePair out of range (-1)

**Comment by paullric** [comment]
Could you provide the in_mesh file “ne30np4_091226_pentagons.nc”?

**Comment by xiaohumengdie** [comment]
2 files can be download : 
https://svn-ccsm-inputdata.cgd.ucar.edu/trunk/inputdata/share/scripgrids/

**Comment by xiaohumengdie** [comment]
I test ne30pg2, ne480pg3，ne60np4. ne30pg2 and ne480pg3 can get the ne30 adjacency list, ne60np4 got the same error.
GenerateConnectivityFile only supports pg grid ?

**Comment by xiaohumengdie** [comment]
I had tested the ne30pg2, ne480pg3,ne60np4 with GenerateConnectivityFile tool. The ne30pg2 and ne480pg3 is ok, but the ne60np4 got the same error. Does the GenerateConnectivityFile not support np4 grid?

**Comment by paullric** [comment]
This should be fixed in commit 1c2cb75c8972e04ab280bbad650c253588074818.  Actually GenerateConnectivityFile did not work previously with meshes that have holes, i.e. not complete coverage of the sphere.  While the mesh you pointed out did have complete coverage, the algorithm that identified coincident nodes in SCRIP files actually was not working correctly.  Because SCRIP files contain redundant node coordinates that need to be identified and removed, the SCRIP format can sometimes cause problems.
