### ISSUE TITLE
Clarifications regarding missing timesteps

### ISSUE THREAD

**Issue by onnyyonn** [ClimateGlobalChange/tempestextremes#54]
I am applying Tempest Extremes on ERA5 MSL data on hourly interval to track extratropical cyclones. I noticed that, for some tracks, some of the time steps are missing. What I mean by that is, the time difference between two consecutive nodes are 2 hours, instead of 1. I would like to know if there is an explanation for it. Is it happening because the node did not move to a different grid in 1 hour time? Or is it because the node disappeared during that timestep?

I am providing my `DetectNodes` and `StitchNodes` configuration here as a reference.

```
DetectNodes \
    --in_data_list data.tmp \
    --out $node_file \
    --searchbymin MSL \
    --closedcontourcmd "MSL,200.0,6.0,0" \
    --mergedist 6.0 \
    --outputcmd  "MSL,min,0" \
    --latname latitude --lonname longitude

StitchNodes \
    --in_list nodeslist.tmp \
    --out XTC.csv \
    --in_fmt "lon,lat,slp" \
    --range 2.0 \
    --mintime "60h" \
    --maxgap "18h" \
    --min_endpoint_dist 12.0 \
    --out_file_format "csv"
```

**Comment by paullric** [comment]
In your configuration below you use "--maxgap 18h"  This means that up to 18h of time is allowed between sequential detections.  The way StitchNodes works is for each detection at each time slice, it looks back across previous time slices to find detected candidate nodes within the prescribed distance.  The maxgap allows StitchNodes to look further back in time to identify that possible companion.  So if there is a gap in the trajectory that is because during the missing time slice there was no candidate node within the 2.0 degree great circle distance allowed.  If the node did not move, but was still a candidate node, then it would appear in the trajectory file.

**Comment by onnyyonn** [comment]
Thank you for the clarification.
